### ISSUE TITLE
Is there any way to bypass the textbox on mobile?

### ISSUE THREAD

**Issue by timetobrawl** [MateusAquino/stardewids#1]
I open the textbox paste the code then click ok and it trims it back to the text limit

![Screenshot_20241114_072747](https://github.com/user-attachments/assets/7a519982-de55-4958-9d5e-b246ae73436d)

**Comment by MateusAquino** [comment]
I haven't tried mobile 1.6 yet, but could you try to use this code and see if it works (I've just reduced the character limit):

```
#$ac${^^
}$tio${^^
}$n A${^^
}$ddI${^^
}$te${^^
}$m 0 5 3
```

If it works I'll reduce the limit on the tool for mobile users... If it doesn't work the only way to cheat would be through debug cheats (which I'll implement soon)

**Comment by timetobrawl** [comment]
Looks like it freaks out when you add multiple lines and put them all on the same line with the character limit

![Screenshot_20241114_155537](https://github.com/user-attachments/assets/e2479781-040d-4192-b58a-2056ec6339cd)

**Comment by MateusAquino** [comment]
ohh that sad, I'll update the website this weekend with a debug mode

**Comment by timetobrawl** [comment]
Alright thanks for the help!

**Comment by timetobrawl** [comment]
Uhhh new thing ive found: after updating to 1.6.14.0 i can no longer use item codes it just say name unavailable

**Comment by MateusAquino** [comment]
@timetobrawl could you verify if following the steps with the "Chat Cheats" mode enabled you can spawn items in the version you are running? If something fails tell me and I'll adjust or improve

**Comment by timetobrawl** [comment]
Works perfectly tysm!
Although you should probably add that you need to tap the date box to open chat before you get questions on how to open chat on mobile

![Screenshot_20241118_185824](https://github.com/user-attachments/assets/f2dc962d-5753-4d73-bee8-32ae8d831475)

**Comment by MateusAquino** [comment]
Thank you for the suggestion I'll add this information to the list until tomorrow :)

**Comment by Dannadannanita** [comment]
> @timetobrawl¿Podrías verificar si siguiendo los pasos con el modo "Chat Cheats" habilitado puedes generar objetos en la versión que estás ejecutando? Si algo falla, dímelo y lo ajustaré o mejoraré.

I'm trying to follow the steps in your blog to activate the chat cheats, but I can't, I want to recover at least a part of the game I lost because of a bug.

**Comment by MateusAquino** [comment]
> I'm trying to follow the steps in your blog to activate the chat cheats, but I can't, I want to recover at least a part of the game I lost because of a bug.

Why exactly you can't? could you describe your problem and where are you stuck?

It would also be helpful if you tell us you version + os

**Comment by Dannadannanita** [comment]
> > I'm trying to follow the steps in your blog to activate the chat cheats, but I can't, I want to recover at least a part of the game I lost because of a bug.
> 
> Why exactly you can't? could you describe your problem and where are you stuck?
> 
> It would also be helpful if you tell us you version + os

I have version 1.6.14.3 for android, I was playing normally, and in the event where Linus teaches to prepare the bait, the game chashed and closed, when I re-entered, all my games disappeared, even their folders were as if the game was new. So I tried to use the commands in the chat in a new game, but this time activating the chat cheats as you indicate, because I don't want to have to do everything I did again, but (I have already slept several days) I don't see the <allowChatCheats> option.

**Comment by MateusAquino** [comment]
@Dannadannanita Sure, but you said you can't activate the chat cheats, right? tell me why and which step are you stuck so I can help you

**Comment by Dannadannanita** [comment]
> @Dannadannanita Sure, but you said you can't activate the chat cheats, right? tell me why and which step are you stuck so I can help you

There is no allowChatCheats option, I don't know if I could add it (or how to do it) and I'm afraid to move to something without knowing
![Screenshot_20241122-150058_ZArchiver](https://github.com/user-attachments/assets/17cdb4a5-250e-4e60-8c0e-a7abdb2caffc)
![Screenshot_20241122-150110_ZArchiver](https://github.com/user-attachments/assets/05e736f0-4198-4356-b6fe-0636cce4ca90)
![Screenshot_20241122-150122_ZArchiver](https://github.com/user-attachments/assets/0ebca936-6e2c-41ad-aba9-f76f76f0e38d)
![Screenshot_20241122-150134_ZArchiver](https://github.com/user-attachments/assets/a0550a71-2946-45d9-88ce-5ae0bd584708)
![Screenshot_20241122-150138_ZArchiver](https://github.com/user-attachments/assets/939ae377-f5ee-4ad9-bcb2-7aacfc45e675)
![Screenshot_20241122-150050_ZArchiver](https://github.com/user-attachments/assets/24cf9fd7-b07b-4cf8-bef2-576e5c4d1016)

**Comment by MateusAquino** [comment]
Oh I guess it's other file, it will have the name of your world with an underline and numbers (such as "MyWorld_201918391"). Try using the magnifying glass icon to search the cheats toggle in the other file. Also make sure you have slept at least one night in this new 1.6.14.3 version for the option to appear.

If you are worried about losing your world please backup these files before anything.

**Comment by Dannadannanita** [comment]
> Supongo que es otro archivo, tendrá el nombre de tu mundo subrayado y números (como "MyWorld_201918391"). Intenta usar el ícono de la lupa para buscar el interruptor de trucos en el otro archivo. Asegúrate también de haber dormido al menos una noche en esta nueva versión 1.6.14.3 para que aparezca la opción.
> 
> Si le preocupa perder su mundo, haga una copia de seguridad de estos archivos antes de hacer cualquier cosa.

This file does not open no matter how hard I try. 
Here is the test in x5 speed 

https://github.com/user-attachments/assets/82541dcc-8573-4ff5-bb3e-7ee9e0ba9c01

**Comment by MateusAquino** [comment]
@Dannadannanita the file size is probably huge, try opening in another text editor if you can, or send the file to your computer to edit there

**Comment by jazxprr** [comment]
i already changed the <allowChatCheats>false to <allowChatCheat>true, but whenever i press the date box the chat box doesn't appear, help...

**Comment by MateusAquino** [comment]
@jazxprr if you are already on 1.6.9+ and using mobile I believe tapping the date should be enough to open the chat, now if you are on PC press the letter "T"

**Comment by jazxprr** [comment]
i'm on mobile, tapping the date isn't really working and i tried it many times now, is there any other way?

**Comment by jazxprr** [comment]
> Works perfectly tysm!
> Although you should probably add that you need to tap the date box to open chat before you get questions on how to open chat on mobile
> 
> ![Screenshot_20241118_185824](https://github.com/user-attachments/assets/f2dc962d-5753-4d73-bee8-32ae8d831475)
> 

how'd you do that? huhu

**Comment by MateusAquino** [comment]
@jazxprr I just stumbled across a youtube video for PC and in the comments some guy said:

> "Consegui no mobile, troca a opção do controle para somente analógico e botões, clica na data e vai aparecer o chat. Se tiver ativado o controle clicar e mover não abre o chat. :)"

Seems like you need to also change the controls settings to "Analog and Buttons" or something before tapping the date, could you try this out?

**Comment by Benn710** [comment]
Hello, I have tried on 1.6.14.6,
changed the chat cheats element to true. but the game is either going back to yesterday, or it won't load my game

**Comment by MateusAquino** [comment]
> Hello, I have tried on 1.6.14.6,
> changed the chat cheats element to true. but the game is either going back to yesterday, or it won't load my game

Hey @Benn710, could you try editing your save in another text editor? Maybe the current editor you're using might be appending extra characters somewhere or breaking encoding, btw always backup your save files before editing manually.

**Comment by monkeycod52** [comment]
Pardon me, it seems that I can't find the word cheat in all the files from my save; the only thing that shows is cheat_summit. I'm currently playing on Android mobile v.14 with a game version of 1.6.15. Any help, please?

**Comment by pazjidia-dot** [comment]
Is this available in IOS?
